### ISSUE TITLE
Add SzReplaceConflictError

### ISSUE THREAD

**Issue by barrycaceres** [senzing-garage/sz-sdk-errors#13]
We need a new error/exception called `SzReplaceConflictError` that will inherit from `SzError` and be used whenever an attempt is made to replace an existing value with a new value only if the existing value is still the same as an expected value that the caller specifies.

Currently this will apply to `SzConfigMgr.replaceDefaultConfigId()` but may apply in the future to an `SzEngine.replaceRecord()` function.

For `G2ConfigMgr.replaceDefaultConfigId()` the error code is currently 7245 -- but this may change based in the next Sprint if Brian decides to make a generic error code to match the more generic "replace conflict" exception.

**Comment by docktermj** [comment]
Fix:

- https://github.com/senzing-garage/sz-sdk-errors/blob/5ac8dd6e835115830cf66e730cc05bcdc5c1adcb/szerrors.json#L1796-L1800
